Algoritmo "Ex01 Reajuste Salarial"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2020
Var
// Seção de Declarações das variáveis 
   a: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Qual seu salário?")
   Leia(a)
   Escreva("Seu novo salário é de: R$", a + a*0.15)

Fimalgoritmo