Algoritmo "Ex03 Celsius Fahrenheit"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2020
Var
// Seção de Declarações das variáveis 
   a: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Temperatura: ")
   Leia(a)
   Escreva(a, "°ºC ou ", (9*a + 160)/5, "ºF")

Fimalgoritmo