Algoritmo "EX04 Kelvin Celsius"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2020
Var
// Seção de Declarações das variáveis 
   a: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Temperatura em Kelvins: ")
   Leia(a)
   Escreva(a - 273, "ºC")

Fimalgoritmo