Algoritmo "Ex10 Real Dolar"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2020
Var
// Seção de Declarações das variáveis 
   a: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Valor em Real: R$")
   Leia(a)
   Escreval("Valor em Dólares: $", a/5.3)

Fimalgoritmo