Algoritmo "Ex11 Euro Real"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2020
Var
// Seção de Declarações das variáveis 
   a: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Quantidade em Euro: ")
   Leia(a)
   Escreval("R$", a*6.26)

Fimalgoritmo