Algoritmo "Ex20 Raio Área"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2020
Var
// Seção de Declarações das variáveis 
   a, b: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Raio: ")
   Leia(a)
   b <- Pi * 2 * a
   Escreva("Área: ", b)

Fimalgoritmo